/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentación;

/**
 *
 * @author XPC
 */
public class frmInicio extends javax.swing.JFrame {
        
    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrestar = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opAgregarPrestamos = new javax.swing.JMenuItem();
        opTablaDePrestamos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpPrestar.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Calculadora De Libros");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        dpPrestar.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpPrestar.setLayer(btnEntrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpPrestarLayout = new javax.swing.GroupLayout(dpPrestar);
        dpPrestar.setLayout(dpPrestarLayout);
        dpPrestarLayout.setHorizontalGroup(
            dpPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPrestarLayout.createSequentialGroup()
                .addGroup(dpPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpPrestarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dpPrestarLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnEntrar)))
                .addContainerGap(660, Short.MAX_VALUE))
        );
        dpPrestarLayout.setVerticalGroup(
            dpPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPrestarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnEntrar)
                .addContainerGap(540, Short.MAX_VALUE))
        );

        jMenu1.setText("Administrador");

        opAgregarPrestamos.setText("Prestamos");
        opAgregarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAgregarPrestamosActionPerformed(evt);
            }
        });
        jMenu1.add(opAgregarPrestamos);

        opTablaDePrestamos.setText("Tabla De Prestamos");
        opTablaDePrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opTablaDePrestamosActionPerformed(evt);
            }
        });
        jMenu1.add(opTablaDePrestamos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrestar)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrestar)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void opAgregarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opAgregarPrestamosActionPerformed
        // TODO add your handling code here:
        frmPrestar prestar = new frmPrestar();
        dpPrestar.add(prestar);
        prestar.show();
    }//GEN-LAST:event_opAgregarPrestamosActionPerformed

    private void opTablaDePrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opTablaDePrestamosActionPerformed
        // TODO add your handling code here:
        frmTablaPrestamos tabla = new frmTablaPrestamos();
        dpPrestar.add(tabla);
        tabla.show();
    }//GEN-LAST:event_opTablaDePrestamosActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        CalculadorDeLibros calculadora = new CalculadorDeLibros();
        dpPrestar.add(calculadora);
        calculadora.show();
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JDesktopPane dpPrestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opAgregarPrestamos;
    private javax.swing.JMenuItem opTablaDePrestamos;
    // End of variables declaration//GEN-END:variables
}
