/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentación;

import Entidades.Prestamo;
import Lógica.Logica;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author XPC
 */
public class frmTablaPrestamos extends javax.swing.JInternalFrame {
    DefaultTableModel elModelo = new DefaultTableModel();
    /**
     * Creates new form frmTablaPrestamos
     */
    public frmTablaPrestamos() {
        initComponents();
        
        String[] titulos = new String[] {"Nombre", "Cedula", "CodigoUsuario", "CodigoBiblio", "NombreBiblio", "CedulaBiblio", "Titulo", "Editorial", "Genero"};
        elModelo.setColumnIdentifiers(titulos);
        tblDatos.setModel(elModelo);
        
        this.RefrescarTabla();
        
    }
    
    
    
    
        public void RefrescarTabla() {
        TableModel tablaModel = this.CompletarTableModel();
        tblDatos.setModel(tablaModel);
    }
    
      
       
       private TableModel CompletarTableModel() {
        try {
            Logica laCapaDeLogica = new Logica();
            List<Prestamo> miListaDePrestamo = laCapaDeLogica.traerTodaLaBaseDeDatos();
            Object[] columnas = new Object[]{"Nombre", "Cedula", "CodigoUsuario", "CodigoBiblio", "NombreBiblio", "CedulaBiblio", "Titulo","Editorial", "Genero"};
            Object[][] datos = new Object[miListaDePrestamo.size()][columnas.length];
            for (int i = 0; i < miListaDePrestamo.size(); i++) {
                datos[i][0] = miListaDePrestamo.get(i).getUsuarioPrestamo().getNombre();
                datos[i][1] = miListaDePrestamo.get(i).getUsuarioPrestamo().getCedula();
                datos[i][2] = miListaDePrestamo.get(i).getUsuarioPrestamo().getCodigoUsuario();
                datos[i][3] = miListaDePrestamo.get(i).getBiblioPrestamo().getCodigoBibliotecologo();
                datos[i][4] = miListaDePrestamo.get(i).getBiblioPrestamo().getNombre();
                datos[i][5] = miListaDePrestamo.get(i).getBiblioPrestamo().getCedula();
                datos[i][6] = miListaDePrestamo.get(i).getLibroPrestamo().getTitulo();
                datos[i][7] = miListaDePrestamo.get(i).getLibroPrestamo().getEditorial();
                datos[i][8] = miListaDePrestamo.get(i).getLibroPrestamo().getGenero();
                
            }
            DefaultTableModel model = new DefaultTableModel(datos, columnas);
            return model;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La tabla no se cargo correctamente", null, 1);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscadorDePrestamos = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jLabel1.setText("Buscador");

        txtBuscadorDePrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorDePrestamosActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscadorDePrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnActualizar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscadorDePrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorDePrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorDePrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorDePrestamosActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        this.RefrescarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtBuscadorDePrestamos;
    // End of variables declaration//GEN-END:variables
}
